---
- name: reload systemd user
  become: true
  become_user: "{{ hermes_user }}"
  command:
    cmd: systemctl --user daemon-reload
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ hermes_uid.stdout }}"
